### ISSUE TITLE
how to setup a prover node on mainnet 

### ISSUE THREAD

**Issue by victerying** [scroll-tech/scroll#1000]
I follow the instruction in folder scroll/prover. When i run ./build/bin/prover ,  i see a very long error message in terminal. I think it may be because I didn't configure the JSON file. But how do I know the url of coordinator and the l2geth node.Or rather, what did I do wrong elsewhere. Could anyone tell me.

**Comment by zakopane262** [comment]
Please follow the instruction on the website. It seems they updated the docs.

**Comment by Thegaram** [comment]
We currently don't allow new 3rd-party provers to join our network. Once this changes we will publish step-by-step instructions.
