### ISSUE TITLE
Issue of deployment 

### ISSUE THREAD

**Issue by ruddeenn1** [scroll-tech/scroll#1051]
I deployed contact address and NFT, you said I didn't during 60 days, any help please

**Comment by ruddeenn1** [comment]
![Screenshot_20231215-050014](https://github.com/scroll-tech/scroll/assets/142293035/08f4aa04-7031-4d44-a6c6-222243b665e7) here it's

**Comment by 0xmountaintop** [comment]
Hi @ruddeenn1, please contact in discord `#Scroll-Origins-Support` channel, you can provide your wallet address and deployment tx hash there.
