### ISSUE TITLE
I deployed contact address and NFT, you said I didn't during 60 days, any help please

### ISSUE THREAD

**Issue by Dambac1** [scroll-tech/scroll#1054]
i did on the reported period and got the confirmation from the mint page. I see a lot of users with the same issue, probably this should be corrected to solve it in a massive way. 
Cheers.

**Comment by 0xmountaintop** [comment]
Hi @Dambac1, please contact in discord `#Scroll-Origins-Support` channel, you can provide your wallet address and deployment tx hash there.
