### ISSUE TITLE
how do I receive

### ISSUE THREAD

**Issue by myuniswap2000** [scroll-tech/scroll#1084]
Hello, how do I receive Tx?

**Comment by Thegaram** [comment]
Hi @myuniswap2000, could you elaborate? Did you send a transaction on Scroll or Scroll Sepolia that is stuck as pending? Or are you looking for a way to retrieve pending transactions using the SDK? Please provide as much detail as possible.

**Comment by myuniswap2000** [comment]
ok

**Comment by myuniswap2000** [comment]
I  use golang dev.
