### ISSUE TITLE
Contributor Code of Conduct

### ISSUE THREAD

**Issue by bensy24** [scroll-tech/scroll#1119]
Is it possible to add language that the complainee will be given a right to defend himself with regards to complaints? Seems like the below is one sided, what about fake complaints ? 

Enforcement
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at [contributor@scroll.io](mailto:contributor@scroll.io). All complaints will be reviewed and investigated promptly and fairly.

All community leaders are obligated to respect the privacy and security of the reporter of any incident.

**Comment by Thegaram** [comment]
Code of Conduct is adopted from GitHub and will not be changed at this time.
