### ISSUE TITLE
Fee refund

### ISSUE THREAD

**Issue by Gbanks2230** [scroll-tech/scroll#1131]
I want to suggest a fee refund on scroll network. This can bring more new users to the network knowing there’s a fee refund on transactions.. it doesn’t have to be 100% refund.. just something the community would appreciate. Thank you

**Comment by Gbanks2230** [comment]
Would be appreciated

**Comment by SeyyidOS** [comment]
The fees on the Scroll network are set up really well, so there's hardly any need to give refunds. This means they've figured out a good balance, making things easier for everyone using the network. It shows they're doing a great job at keeping costs fair and making sure users are happy.
