### ISSUE TITLE
Missing else block

### ISSUE THREAD

**Issue by Adnankalay** [scroll-tech/scroll#1144]
https://github.com/scroll-tech/scroll/blob/d4cc0eaab99d7658a2c1177b827990d827966cba/rollup/internal/controller/sender/sender.go#L449

According to MISRA coding standard it is adviced to add an else block for **if-else if** statements for code completeness and in order to catch unforeseen run time scenarios. Although it is escpecailly crucial for mission critical codes, I think this measure can be applied to widely used blockchain codes such as Scroll's also.

**Comment by georgehao** [comment]
just close it
