### ISSUE TITLE
Sometimes interaction fails with contract made on nfts2me 

### ISSUE THREAD

**Issue by demvy** [scroll-tech/scroll#1202]
I have often exceptions when trying to use contract (mint nft) on Scroll from nfts2.me. **Exception code is 0xc288bf8f**, as I understand, it is **InvalidMintFee()** error. I do not think that it is only client problem, more the problem with rpc/connection because bug reproduces on different setups (please look below). Maybe, should be fixed.

This bug is new one, haven't seen issue in February or earlier, started to see from 5-7th of March (I'm using Scroll from December).

Bug is reproducible, sometimes from the 1st time (mostly), sometimes from 5th...
Exception occurs on both metamask + browser setup or python script automation. In python script error comes more often, I would say, contract interaction is more unsuccessful than OK.

Setup:
**MetaMask 11.12.4**, ID: nkbihfbeogaeaoehlefnkodbefgpgknn
**Google Chrome** version **122.0.6261.128** (Official Build) (64-bit)

**Comment by Thegaram** [comment]
This seems to be an application error, have you tried contacting the maintainers of this dapp?

**Comment by demvy** [comment]
No, I haven't contacted them yet because wanted to know your opinion. This issue comes only for Scroll network, I haven't seen such errors in zkSync or Mint network testnet. 

Mechanics of that dapp: user creates nft collection, dapp has own templates for editions/collections/collectibles on big amout of blockchains. Dapp creates contract by templates, tamplated frontend that can be customized and that's all. Example of edition: https://scroll-duck-commander.nfts2.me/

IMO, contracts for different L2 networks there will be the same or almost the same. That's why I've thought, it could be some connectivity problem with scroll/gas issue

Do you think, it is their error?

**Comment by Thegaram** [comment]
Yes, since the error is returned from the Solidity contract itself, it's an application error.
