### ISSUE TITLE
Transaction failing with error

### ISSUE THREAD

**Issue by capitalzguru** [scroll-tech/scroll#1206]
Fail with error 'Return amount is not enough.

https://scrollscan.com/tx/0x8b03676f07af2828b2451b0ffeed76353dddee7621cc3a5e1f9a66586d804eb7
![Screenshot_1](https://github.com/scroll-tech/scroll/assets/135963861/60d5cc43-41eb-4404-9e99-7c68400b99b8)

**Comment by Thegaram** [comment]
This is an error returned by the KyberSwap contract, please contact their team for support.
