### ISSUE TITLE
docs: update links in contracts/src/misc/ERC2771Forwarder.sol 

### ISSUE THREAD

**Issue by alexanderblv** [scroll-tech/scroll#1226]
https://github.com/scroll-tech/scroll/blob/ed0e0e4c188cca1fd2a3ae71a0be03220be0050f/contracts/src/misc/ERC2771Forwarder.sol#L384

Line 384, the data is outdated. A big update has been released. Here is a new link:
https://docs.soliditylang.org/en/v0.8.25/control-structures.html#panic-via-assert-and-error-via-require

In the new version, the information is more complete and clear

For some reason I can't create a Pull Request and because of this I have to create Issue

**Comment by Thegaram** [comment]
This file was copied directly from OpenZeppelin, as the comment on the top says.
