### ISSUE TITLE
Testnet FeedBack

### ISSUE THREAD

**Issue by Disillusion021** [scroll-tech/scroll#1338]
The trx in Scroll is a little bit slow.
About 10-15 minutes to confirm.
It would be nice if it was faster.

**Comment by Thegaram** [comment]
On Scroll Sepolia? It should be very fast, there's no congestion on the testnet.

**Comment by Disillusion021** [comment]
On scroll mainnet. Why did I wait more than 18 minutes to get to the scroll
chain?
![image](https://github.com/scroll-tech/scroll/assets/96580191/ebe21f14-e27e-4c14-ab86-18cc4be51b2a)

**Comment by Disillusion021** [comment]
Sorry. I got it wrong. Maybe it's because the staking needs to wait for the next block to be confirmed.

**Comment by Thegaram** [comment]
Got it, thanks for your feedback. Please contact our team on Discord for technical support if needed.
