### ISSUE TITLE
Scroll Etherscan Block Explorer

### ISSUE THREAD

**Issue by blocks3ck** [scroll-tech/scroll#1345]
The code IDE couldn't open the contract

![image](https://github.com/scroll-tech/scroll/assets/126947358/82369b30-b55c-4d61-8126-638f4a62c012)

The right url should be https://vscode.blockscan.com/scroll/0xaa111c62cdeef205f70e6722d1e22274274ec12f ,but when I click IDE. The browser open to https://vscode.blockscan.com//0xaa111c62cdeef205f70e6722d1e22274274ec12f

**Comment by Thegaram** [comment]
Thank you, we reported this to the Scrollscan team, they will fix it soon.
