### ISSUE TITLE
Encountered problems running tests - Cancun

### ISSUE THREAD

**Issue by Kajko25** [scroll-tech/scroll#1373]
I don't know if I'm creating a thread in the right place but 2 days ago I encountered problems running tests due to the use of "blobhash" in "ScrollChain.sol".... I thought this was introduced in the Cancun update

Does anyone else have this problem or know a way to solve it?

Best regards
Kajko25

**Comment by Thegaram** [comment]
You can compile using `FOUNDRY_EVM_VERSION="cancun" forge build` or `forge build --evm-version cancun`.
