### ISSUE TITLE
Mainnet & Testnet Wei (Calculation) Issue

### ISSUE THREAD

**Issue by berkeguleryuz** [scroll-tech/scroll#1386]
Hello you will see same contracts as Sepolia and Mainnet:

They are not working in the same process. Because the explorer data on the mainnet side is not calculated as wei. But in testnet (Sepolia) is working correctly as well. We are experiencing many problems because of this. Can this process be controlled and corrected?

https://sepolia.scrollscan.com/address/0xd73D676AA7935FEc7ADA64AE910237C735E13a64#readContract < sepolia
https://scrollscan.com/address/0xdca8d621e17f0f820b403bc7f9edab8fc771a8d6#readContract < mainnet

![mainnet1](https://github.com/scroll-tech/chain-monitor/assets/62810679/af80a32a-4596-4b9e-909c-446bc557a4a1)
Mainnet1
![mainnet2](https://github.com/scroll-tech/chain-monitor/assets/62810679/d35dacc5-6bfd-49c8-9c52-dfef15061bd2)
Mainnet2
![Sepolia](https://github.com/scroll-tech/chain-monitor/assets/62810679/9b72e8d5-8c31-4412-8227-252340ac0daf)
Sepolia1
![Sepolia2](https://github.com/scroll-tech/chain-monitor/assets/62810679/ad3732e3-9c0c-42d7-b617-4fd7517731c3)
Sepolia2
![Sepolia3](https://github.com/scroll-tech/chain-monitor/assets/62810679/3caa56cc-c7dd-4fb5-8097-ec7d156858b9)
Sepolia3

So we are getting issue about that. Could you kindly help us with that?

**Comment by Thegaram** [comment]
The ERC20 standard allows tokens to specify their decimals. While it is usually set as `18` (i.e. matching the wei-to-ETH granularity), there are well-known exceptions like mainnet USDT, which uses `6`. To make your code robust, you should consider `decimals` in your contract's logic.
