### ISSUE TITLE
I can't find the blob consystency check code

### ISSUE THREAD

**Issue by hduoc2003** [scroll-tech/scroll#1387]
Hi guys, I am new here.
As I know, the contracts was updated to deal with EIP-4844, but I can not find the blob consystency check code in prover folder. Maybe I'm missing some concepts, is there any documentation on proof creation flow?

**Comment by Thegaram** [comment]
Hey, welcome!

For the proving part, the consistency check is done in the aggregation circuit. You can find the code here: https://github.com/scroll-tech/zkevm-circuits/tree/develop/aggregator/src/aggregation

The contract part is here: https://github.com/scroll-tech/scroll/blob/develop/contracts/src/L1/rollup/ScrollChain.sol#L455

The blob data proof is constructed here: https://github.com/scroll-tech/da-codec/blob/main/encoding/codecv1/codecv1.go#L419

Hope that helps!
