### ISSUE TITLE
Can't create a Scroll canvas username to start badges activity

### ISSUE THREAD

**Issue by WinzerQ** [scroll-tech/scroll#1525]
The checking is going forever, even i changed browser, clear cash and tried several nicknames.
<img width="1702" alt="Снимок экрана 2024-09-27 в 14 36 44" src="https://github.com/user-attachments/assets/3418a5f3-5fbe-45aa-b546-80677463549d">

**Comment by Thegaram** [comment]
Thanks for reporting this. Please ask for assistance in the [dev support channel](https://discord.com/channels/853955156100907018/1028102371894624337) on Discord.
