### ISSUE TITLE
[Enhance] Use testcontainer instead of start docker engine

### ISSUE THREAD

**Issue by georgehao** [scroll-tech/scroll#436]

**Comment by bzarka** [comment]
Hi,

Using Testcontainers is an elegant approach for integration testing involving Docker containers. Here is an example modification to integrate Testcontainers into your code:

import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
public class YourIntegrationTest {

    @Container
    private static final GenericContainer<?> yourServiceContainer = new GenericContainer<>("your-docker-image:tag")
            .withExposedPorts(8080); // Adjust the port if needed

    @Test
    public void testYourService() {
        String baseUrl = "http://" + yourServiceContainer.getHost() + ":" + yourServiceContainer.getMappedPort(8080);
        
        // Perform your integration test using the baseUrl
    }
}

**Comment by Thegaram** [comment]
Closing as done, please reopen if it's still an issue.
