### ISSUE TITLE
handle reorg in watchers

### ISSUE THREAD

**Issue by 0xmountaintop** [scroll-tech/scroll#924]

**Comment by bzarka** [comment]
Hi,

To handle reorganizations in watchers in the context of blockchain or decentralized systems, you typically need to implement mechanisms to detect and react to chain reorganizations. Here's a general outline of how you might approach this:

1. **Monitor Chain Head Changes**: Keep track of the current chain head or block height that your system is synced with.

2. **Subscribe to Chain Head Events**: Use the APIs or libraries provided by your blockchain platform to subscribe to chain head events. These events indicate changes in the main chain, including new blocks being added or chain reorganizations occurring.

3. **Handle Reorganizations**: When a chain reorganization event occurs, your system needs to handle it appropriately. This typically involves rolling back any transactions or state changes that were based on the invalidated portion of the chain and then reapplying transactions from the new chain head. The exact steps will depend on your system's architecture and requirements.

4. **Update Watchers and State**: After handling the reorganization, update any relevant watchers or state in your system to reflect the new chain head and the current valid state of the chain.

5. **Retry or Notify**: Depending on your system's requirements, you may need to retry any transactions or actions that were affected by the reorganization, or you may need to notify users or other components of the system about the reorganization and its implications.

6. **Testing and Monitoring**: Ensure that your system's handling of chain reorganizations is tested thoroughly and regularly. Monitor your system for any issues related to reorganizations and be prepared to address them promptly.

Remember that handling chain reorganizations can be complex, especially in decentralized systems where multiple actors may be involved. It's important to thoroughly understand the implications of chain reorganizations for your system and to implement robust mechanisms to handle them effectively.

**Comment by jayaabadi88** [comment]
not yet

**Comment by Farhoo** [comment]
agree

**Comment by nafasho** [comment]
nice work

**Comment by Thegaram** [comment]
Closing as this will be addressed as part of a larger project.
